### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by supunkavinda** [hyvor/hyvor-talk-comments#1]
Back-end
- [x] Reactions
- [x] Comments (GET)
- [x] Comments (POST)
- [ ] Comments (PATCH)
- [x] Voting
- [x] Notifications 
- [ ] Single Sign-on

Front-end UI
- [x] Reactions
- [ ] Ratings
- [ ] Rich Text Editor (Currently working on this)
- [ ] Commets Loading
- [ ] Comment publishing
- [ ] Notifications
- [ ] Online Count & Visitors Showing
- [ ] Real-time updates
- [ ] Moderator actions

**Comment by supun-io** [comment]
- [ ] Collapse longer comments
